name: Run Rudaw API Script

on: 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      id: run_script
      run: python rudaw_api.py

    - name: Output result
      run: echo "${{ steps.run_script.outputs.result }}"
